# Generated by Django 3.1.2 on 2020-10-17 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_category', models.CharField(db_index=True, default=None, max_length=64, verbose_name='name_category')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_place', models.CharField(db_index=True, default=None, max_length=64, verbose_name='name_place')),
                ('description_place', models.CharField(db_index=True, default=None, max_length=2048, verbose_name='description_place')),
                ('cost_place', models.FloatField(db_index=True, default=None, max_length=64, verbose_name='cost_place')),
                ('address_place', models.CharField(db_index=True, default=None, max_length=1024, verbose_name='address_place')),
                ('pictures_place', models.ImageField(db_index=True, default=None, upload_to='images/', verbose_name='pictures_place')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WPApp.category', verbose_name='category')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_favorite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WPApp.place', verbose_name='place_favorites')),
                ('user_favorite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user_favorite')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_comment', models.CharField(default=None, max_length=200, verbose_name='text_comment')),
                ('author_comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='author_place')),
                ('place_comment', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='WPApp.place', verbose_name='category_comment')),
            ],
        ),
    ]
