# Generated by Django 3.0.2 on 2020-01-02 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_place', models.CharField(db_index=True, max_length=64, verbose_name='name_place')),
                ('category', models.IntegerField(choices=[(1, 'cinema'), (2, 'museum'), (3, 'park')], verbose_name='category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_comm', models.CharField(max_length=200)),
                ('place_comm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HTApp2_0.Place')),
            ],
        ),
    ]
