# Generated by Django 3.0.2 on 2020-01-02 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HTApp2_0', '0002_auto_20200102_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='address_place',
            field=models.CharField(db_index=True, default=None, max_length=1024, verbose_name='address_place'),
        ),
        migrations.AddField(
            model_name='place',
            name='cost_place',
            field=models.FloatField(db_index=True, default=None, max_length=64, verbose_name='cost_place'),
        ),
        migrations.AddField(
            model_name='place',
            name='description_place',
            field=models.CharField(db_index=True, default=None, max_length=2048, verbose_name='description_place'),
        ),
        migrations.AddField(
            model_name='place',
            name='pictures_place',
            field=models.ImageField(db_index=True, default=None, upload_to='', verbose_name='pictures_place'),
        ),
        migrations.AlterField(
            model_name='place',
            name='name_place',
            field=models.CharField(db_index=True, default=None, max_length=64, verbose_name='name_place'),
        ),
    ]
