# Generated by Django 3.0.2 on 2020-01-03 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HTApp2_0', '0004_auto_20200102_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='pictures_place',
            field=models.ImageField(db_index=True, default=None, upload_to='images/', verbose_name='pictures_place'),
        ),
    ]
