# Generated by Django 3.0.2 on 2020-01-03 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HTApp2_0', '0005_auto_20200103_0659'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_favorite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HTApp2_0.Place', verbose_name='place_favorites')),
                ('user_favorite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user_favorite')),
            ],
        ),
        migrations.DeleteModel(
            name='Favorites',
        ),
    ]
