# Generated by Django 3.0.1 on 2020-01-06 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HTApp2_0', '0006_auto_20200103_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author_comment',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='place_comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='category_comment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='HTApp2_0.Category', verbose_name='category_comment'),
        ),
        migrations.AddField(
            model_name='deal',
            name='count_ticket',
            field=models.IntegerField(default=1, verbose_name='count_ticket'),
        ),
        migrations.AddField(
            model_name='deal',
            name='privileges_deal',
            field=models.BooleanField(default=None, verbose_name='privileges_deal'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='name_deal',
            field=models.CharField(default=None, max_length=200, verbose_name='name_deal'),
        ),
    ]
