# Generated by Django 3.0.1 on 2020-01-08 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HTApp2_0', '0007_auto_20200106_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='category_comment',
        ),
        migrations.RemoveField(
            model_name='place',
            name='author_place',
        ),
        migrations.AddField(
            model_name='comment',
            name='author_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='author_place'),
        ),
        migrations.AddField(
            model_name='comment',
            name='place_comment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='HTApp2_0.Place', verbose_name='category_comment'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='privileges_deal',
            field=models.BooleanField(default=0, verbose_name='privileges_deal'),
        ),
    ]
